server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql:///spring_shiro
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:com/Still/mapping/*.xml
  type-aliases-package: com.Still.domain
